spring.application.name=event_management_backend

#custom port
server.port=9001


# prefix on url
server.servlet.context-path = /sweven_events

# my sql connection
#spring.datasource.url=${DATASOURCE_URL}
#spring.datasource.username=${DATASOURCE_USER}
#spring.datasource.password=${DATASOURCE_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver



# Turn Off spring boot banner
spring.main.banner-mode=off

# Reduce logging level . Set to warn
#logging.level.root = warn


#spring.security.basic.enabled=true
#spring.security.user.name=root
#spring.security.user.password=ritik768

spring.datasource.url=jdbc:postgresql://localhost:5432/eventmanagement
spring.datasource.username=eventmanagement_user
spring.datasource.password=ritik@768
spring.datasource.driver-class-name=org.postgresql.Driver



# Reduce logging level . Set to warn
#logging.level.root = warn


#spring.security.basic.enabled=true
#spring.security.basicUser.name=root
#spring.security.basicUser.password=ritik768

logging.level.org.springframework.jdbc.datasource=DEBUG
logging.level.com.zaxxer.hikari=DEBUG

#redis config
spring.data.redis.host=localhost
spring.data.redis.port=6379

#file config
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=100MB
spring.servlet.multipart.max-request-size=100MB

#Razorpay
razorpay.keyId=rzp_test_xxxxxxxx
razorpay.keySecret=xxxxxxxxxxxx


